---
- name: Create haproxy config directory
  file:
    path: "/etc/haproxy"
    state: directory

- name: Upload haproxy configuration
  template:
    src: haproxy.cfg.j2
    dest: "/etc/haproxy/haproxy.cfg"
  notify: reload haproxy

- name: Install haproxy
  package:
    state: present
    name:
    - haproxy

- name: Start haproxy service
  service:
    name: haproxy
    state: started
    enabled: yes

