---
- name: Remove swapfile from /etc/fstab
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none
  register: swap_config_result

- name: Disable swap
  command: swapoff -a
  when: swap_config_result.changed
