---
- name: Install docker
  package:
    state: present
    name:
    - docker-ce
    - docker-ce-cli

- name: Start docker service
  service:
    name: docker
    state: started
    enabled: yes

- name: Add {{ docker_user}} user to docker group
  user:
    name: "{{ docker_user }}"
    group: docker

- name: Install python-pip
  package:
    state: present
    name: python3-pip

- name: Install docker-py
  pip:
    name: docker-py

