---
- name: update kernel settings
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: "1"
    sysctl_set: yes
    state: present
    reload: yes

- name: add Kubernetes' YUM repository
  yum_repository:
    name: Kubernetes
    description: Kubernetes YUM repository
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    gpgcheck: yes

- name: Install Kubernetes binaries
  yum:
    state: latest
    name:
    - kubelet
    - kubeadm
    - kubectl

- set_fact:
    node_ip: "{{ ansible_all_ipv4_addresses | ipaddr('192.0.0.0/8') | first }}"

- name: Copy Kubernetes configuration file
  template:
    src: templates/k8s.conf
    dest: /etc/sysctl.d/k8s.conf

- name: Copy kubelet service system configuration
  template:
    src: kubelet.j2
    dest: /etc/sysconfig/kubelet
  notify:
    - reload systemd
    - restart kubelet

- meta: flush_handlers

- name: Start and Enable the kubelet
  service:
    name: kubelet
    state: started
    enabled: yes
