---
- name: Install essential packages
  yum:
    state: latest
    name:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2
    - epel-release
    - nc
    - net-tools
    - tcpdump
    - tree
    - nfs-utils

