---
- name: Setup kubeconfig for {{ kubernetes_user }} user
  shell: |
   mkdir -p /home/{{ kubernetes_user }}/.kube
   cp -i /etc/kubernetes/admin.conf {{ kubeconfig_location }}
   chown {{ kubernetes_user }}:{{ kubernetes_user }} {{ kubeconfig_location }}
  when: cluster_health.rc != 0

- name: install network add-on
  command: "kubectl apply -f https://docs.projectcalico.org/v3.17/manifests/canal.yaml --kubeconfig={{ kubeconfig_location }}"

- name: Wait for master to be ready
  shell: "kubectl get nodes --kubeconfig={{ kubeconfig_location }}"
  register: nodes
  until:
    - '" NotReady " not in nodes.stdout'
  retries: 30
  delay: 10

