---
- name: Initialize Kubernetes cluster
  become: true
  shell: |
    kubeadm init \
      --pod-network-cidr={{ pod_subnet }} \
      --control-plane-endpoint={{ control_plane_endpoint }} \
      --apiserver-advertise-address={{ node_ip }} \
      --upload-certs
  register: master_init_output

- name: Save master init output
  copy:
    content: "{{ master_init_output.stdout }}"
    dest: "/home/{{ kubernetes_user }}/master_init_output"

- name: Extract master join command
  shell: |
    cat /home/{{ kubernetes_user }}/master_init_output | grep -oPz 'kubeadm\sjoin(.|\n)+$' | head -3 > /home/{{ kubernetes_user }}/master_join_cmd

- name: Copy kubeconfig to {{ kubeconfig_location }}
  become: true
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "{{ kubeconfig_location }}"
    remote_src: true
    owner: "{{ kubernetes_user }}"
    group: "{{ kubernetes_user }}"

- name: Upload network add-on configuration
  template:
    src: kube-flannel.yml.j2
    dest: "/home/{{ kubernetes_user }}/kube-flannel.yml"

- name: Install network add-on
  command: "kubectl apply -f /home/{{ kubernetes_user }}/kube-flannel.yml"

- import_tasks: wait-for-master.yml

