---
- name: Check node status
  shell: "kubectl get nodes --kubeconfig={{ kubeconfig_location }} | grep {{ ansible_fqdn }} | grep -v NotReady"
  register: node_status
  ignore_errors: yes

- name: Copying token to worker nodes
  copy:
    src: "{{ kubeadm_join_token_path }}"
    dest: "{{ kubernetes_host_dir }}/conf/kubeadm_join_token"
  when: node_status.rc != 0 or node_status.stdout_lines | length==0

- name: join master replica node
  shell: |
   kubeadm reset -f
   KUBE_JOIN_CMD="$(cat {{ kubernetes_host_dir }}/conf/kubeadm_join_token | grep -oPz 'kubeadm\sjoin(.|\n)*?\n$') --apiserver-advertise-address={{ node_ip }}"
   bash -c "${KUBE_JOIN_CMD}"
  when: node_status.rc != 0 or node_status.stdout_lines | length==0

- import_tasks: finalize-master.yml
  when: node_status.rc != 0 or node_status.stdout_lines | length==0

