---
- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /etc/kubernetes
    - /var/log/kubernetes/audit
    - "{{ kubernetes_host_dir }}/conf"

- name: Copy audit policy configuration
  copy:
    src: audit-policy.yml
    dest: /etc/sysctl.d/audit-policy.yml

- name: Copy Kubernetes configuration
  template:
    src: kubeadm-config.yml.j2
    dest: "{{ kubernetes_host_dir }}/conf/kubeadm-config.yml"
  when: inventory_hostname == groups["master"][0]

- name: Check cluster health
  shell: "kubectl get cs --kubeconfig={{ kubeconfig_location }}"
  register: cluster_health
  ignore_errors: yes

- import_tasks: initiate-master.yml
  when: inventory_hostname == groups["master"][0] and cluster_health.rc != 0

- import_tasks: join-master.yml
  when: inventory_hostname != groups["master"][0]

