---
- name: Create /home/{{ kubernetes_user }}/.kube directory
  file:
    path: "/home/{{ kubernetes_user }}/.kube"
    state: directory
    owner: "{{ kubernetes_user }}"

- name: Check cluster health
  shell: kubectl get cs
  register: cluster_health
  ignore_errors: yes
  changed_when: false

- import_tasks: initiate-master.yml
  when: inventory_hostname == groups["master"][0] and cluster_health.rc != 0

- import_tasks: join-master.yml
  when: inventory_hostname != groups["master"][0]

