---
- name: Check node status
  shell: "kubectl get nodes | grep -i {{ ansible_hostname }} | grep -v NotReady"
  register: node_status
  ignore_errors: yes
  changed_when: false

- name: Join worker node
  block:
    - name: Create /home/{{ kubernetes_user }}/.kube directory
      file:
        path: "/home/{{ kubernetes_user }}/.kube"
        state: directory
        owner: "{{ kubernetes_user }}"

    - name: Generate join token
      shell: kubeadm token create --print-join-command
      register: kubeadm_join_cmd
      delegate_to: "{{ groups['master'][0] }}"

    - name: Execute join command
      become: true
      shell: "{{ kubeadm_join_cmd.stdout }}"

    - name: Get kubeadm configuration from first master
      shell: "cat {{ kubeconfig_location }}"
      register: config_file_output
      delegate_to: "{{ groups['master'][0] }}"

    - name: Set kubeadm configuration
      copy:
        content: "{{ config_file_output.stdout }}"
        dest: "{{ kubeconfig_location }}"

    - name: Wait for worker to be ready
      shell: "kubectl get nodes | grep {{ ansible_hostname }}"
      register: nodes
      until:
        - '" Ready " in nodes.stdout'
      retries: 30
      delay: 10

    - name: label worker node
      shell: "kubectl label nodes {{ ansible_hostname }} node-role.kubernetes.io/worker=worker"

  when: node_status.rc != 0 or node_status.stdout_lines | length==0
