---
- name: reload sysctl
  command: sysctl --system

- name: restart containerd
  service:
    name: containerd
    state: restarted

- name: restart docker
  service:
    name: docker
    state: restarted

- name: restart kubelet
  service:
    name: kubelet
    state: restarted
