---
- name: Create directories
  file:
    path: "{{ kubernetes_host_dir }}/conf"
    state: directory

- name: Copy token to worker nodes
  copy:
    src: "{{ kubeadm_join_token_path }}"
    dest: "{{ kubernetes_host_dir }}/conf/kubeadm_join_token"

- name: Check node status
  shell: "kubectl get nodes --kubeconfig={{ kubeconfig_location }} | grep {{ ansible_fqdn }} | grep -v NotReady"
  register: node_status
  ignore_errors: yes

- name: Join worker node
  shell: |
   kubeadm reset -f
   cat {{ kubernetes_host_dir }}/conf/kubeadm_join_token | tail -2 | sh
  when: node_status.rc != 0 or node_status.stdout_lines | length==0

- name: Setup kubeconfig for {{ kubernetes_user }} user
  shell: |
   mkdir -p /home/{{ kubernetes_user }}/.kube
   cp -i /etc/kubernetes/kubelet.conf {{ kubeconfig_location }}
   chown {{ kubernetes_user }}:{{ kubernetes_user }} {{ kubeconfig_location }}
  when: node_status.rc != 0 or node_status.stdout_lines | length==0

- name: Wait for workers to be ready
  shell: "kubectl get nodes --kubeconfig={{ kubeconfig_location }}"
  register: nodes
  until:
    - '" NotReady " not in nodes.stdout'
  retries: 30
  delay: 10

- name: label worker node
  shell: "kubectl label nodes {{ ansible_fqdn }} nodetype=worker --kubeconfig={{ kubeconfig_location }}"
  when: node_status.rc != 0 or node_status.stdout_lines | length==0

