- hosts: all
  become: true
  roles:
    - name: k8s
      tags: [base]

- hosts: haproxy
  become: true
  roles:
    - name: haproxy
      tags: [base, haproxy]

- hosts: etcd
  become: true
  roles:
   - name: etcd
     tags: [etcd]

- hosts: master
  roles:
    - name: master
      tags: [master]

- hosts: node
  roles:
    - name: node
      tags: [worker]
