- hosts: all
  become: true
  roles:
    - name: k8s
      tags: [base]

- hosts: haproxy
  become: true
  roles:
    - name: haproxy
      tags: [base, haproxy]

- hosts: master
  roles:
    - name: master
      tags: [master]

- hosts: worker
  roles:
    - name: worker
      tags: [worker]

